CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    type VARCHAR(255),
    capacity INTEGER NOT NULL,
    location VARCHAR(150) NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP(6) NOT NULL,
    end_time TIMESTAMP(6) NOT NULL,
    purpose VARCHAR(250),
    status VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    resource_id BIGINT NOT NULL REFERENCES resource(id)
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(500) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMP(6) NOT NULL,
    revoked BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reservation_resource_interval
    ON reservation (resource_id, status, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_reservation_user_status
    ON reservation (user_id, status);